services:
  ros2-jazzy-mola:
    build:
      context: .
      args:
        - USER_UID=${UID:-1000}
        - USER_GID=${GID:-1000}
    image: ros2-jazzy-custom
    container_name: mola_container
    network_mode: "host"
    stdin_open: true
    tty: true
    command: bash # This ensures the entrypoint executes 'bash' at the end
    environment:
      - DISPLAY=${DISPLAY}
      # this needs "sudo apt install nvidia-container-toolkit" in the host!!
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,compute,utility,display
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
      # Optional: specify the DDS middleware if needed
      #- RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

      # Map your local MCAP folder to /data inside the container
      - ${MOLA_DATASETS:-/tmp}:${MOLA_DATASETS_CONTAINER:-/tmp4}:rw

    # --- GPU Resource Reservation (Modern Compose V2 Syntax) ---
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
